version: '3'

services:
    php:
        image: swoole-dev
        build:
            context: .
        ports:
            - 80:80
        volumes:
            - ./tests:/code/tests
            - ./src:/code/src